version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: DMH-DB
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

  eureka-server:
    build: eureka-server/
    ports:
      - 8761:8761

  config-server:
    build: config-server/
    ports:
      - 8888:8888
    depends_on:
      - eureka-server

  gateway-service:
    build: gateway/
    ports:
      - 8084:8084
    depends_on:
      - eureka-server

  users-service:
    build: users-service/
    ports:
      - 8082:8082
    depends_on:
      - eureka-server

  accounts-service:
    build: accounts-service/
    ports:
      - 8085:8085
    depends_on:
      - eureka-server

volumes:
  mysql-data:

